[project]
name = "tik-tok-streak-saver"
version = "0.1.0"
description = "Hello CLI"
requires-python = ">=3.11"
dependencies = [
    "playwright>=1.58.0",
    "typer=>0.24.1 "
]

[project.scripts]
hello = "hello.hello:cli"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"